### ISSUE TITLE
[Discussion] Necessity of unit tests

### ISSUE THREAD

**Issue by farkidev** [moszinet/BKKCrypt#111]
If this repo really want to remain faithful to the original implementation than I think there should be no tests at all.

**Comment by gtgt** [comment]
Tests protects the original implementation :)

**Comment by Pozo** [comment]
Unit tests don't pay the bills, features do!

**Comment by Sasszem** [comment]
If we want the original, then we need to be corrupt.

**Comment by Sasszem** [comment]
![get](https://user-images.githubusercontent.com/9491836/28574776-2faf69e0-714f-11e7-902c-f3f76fcfd294.jpeg)

**Comment by moszinet** [comment]
Can I please ask everybody, that we should leave politics out of this repository. Just let's be professionals and implement the BKKCrypt algo ;)

**Comment by moszinet** [comment]
Sasszem, I just deleted your image :) - I hope it's okay :)
