### ISSUE TITLE
Missing unit tests

### ISSUE THREAD

**Issue by levend** [moszinet/BKKCrypt#19]
During my daily work, I found very useful to have such an extensive collection of the state of the art BKKCrypt algorithm, however I cannot be sure that they are working properly, since most of the samples are missing unit tests.

Please in the future only accept pull requests with proper tests, and indicate this in the contribution guide.

**Comment by moszinet** [comment]
Levend, I completely agree. I will open tasks for each language, and add wording about including unit tests with future contributions.

**Comment by moszinet** [comment]
Dear Levend, I added information about the necessity of the unit tests, and created separate issues for each language. Now it's time for the community to pick these issues up.

**Comment by akoskovacs** [comment]
We should have a guide on how unit tests must look like, or at least an example.
The guide/example has to answer the following: 
- What should be the structure? One main `Tests` folder or one sub-folder under each language?
- Test automation?
    - Makefiles, or other build systems?
    - One test script to build all?
    - Or maybe, just manual invocation?
- What should the tests include?
- Style?
- Test frameworks?
- Language? (some languages can be tested from others)
- Etc...
